# Generated by Django 5.0.1 on 2024-01-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Введите широту перевала', verbose_name='Широта перевала')),
                ('longitude', models.FloatField(help_text='Введите долготу перевала', verbose_name='Долгота перевала')),
                ('height', models.IntegerField(help_text='Введите высоту перевала', verbose_name='Высота перевала')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otc', models.CharField(max_length=100, verbose_name='Отчество')),
                ('phone', models.IntegerField(unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NW', 'Новое'), ('PN', 'В работе'), ('AC', 'Принято'), ('RJ', 'Не принято')], default='NW', max_length=2)),
                ('beautyTitle', models.TextField(help_text='Введите название перевала', verbose_name='Название перевала')),
                ('title', models.TextField(blank=True, help_text='Введите описание перевала', verbose_name='Описание')),
                ('other_titles', models.TextField(blank=True, help_text='Введите другое название перевала', verbose_name='Другое название перевала')),
                ('connect', models.TextField(blank=True, help_text='Введите что соединяет перевал', verbose_name='Что соединяет перевал')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passes.coords')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes.users')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото перевала')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passes.pereval_added')),
            ],
        ),
    ]
